## buildspec
version: 0.2

## AWS CodeBuild Batch configuration
batch:
  fast-fail: false
  build-list:
    - identifier: cypresse2etests
      buildspec: batch_build1.yml
      env:
        variables:
          IMAGE: public.ecr.aws/cypress-io/cypress/browsers:node12.14.1-chrome85-ff81